services:
  backend:
    image: backend
    build:
      context: .
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: user
      DB_USER: root
      DB_PASSWORD: p@ssw0rd
      SMS_V1_SERVICE_ENDPOINT: "smsv1:8081"
    ports:
      - 8080:8080
      - 8081:8081
    command: ["./wait-for-it.sh", "db:3306", "--strict", "--timeout=300", "--", "/backend"]
    volumes:
      - "./wait-for-it/wait-for-it.sh:/wait-for-it.sh"
  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
    ports:
      - 3306:3306
    volumes:
      - ./data/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
