[mysql]
  dbname    = "{{ .Env.DB_NAME }}"
  host      = "{{ .Env.DB_HOST }}"
  port      = {{ .Env.DB_PORT }}
  user      = "{{ .Env.DB_USER }}"
  pass      = "{{ .Env.DB_PASSWORD }}"
  sslmode   = "{{ .Env.DB_SSL_MODE }}"
