// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	JWTAudienceSecret  string
	JWTDenylist        string
	SMSOtpVerification string
	User               string
}{
	JWTAudienceSecret:  "jwt_audience_secret",
	JWTDenylist:        "jwt_denylist",
	SMSOtpVerification: "sms_otp_verification",
	User:               "user",
}
