name: ci

on:
  - push

jobs:
  proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Setup buf
        uses: bufbuild/buf-setup-action@v0.5.0
        with:
          version: "1.0.0-rc5"

      - name: Install clang-format
        run: |
          sudo apt-get install -y clang-format-12

      - name: Check Format
        run: |
          make check-proto

      - name: Lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"

      - name: Detect Breaking Changes
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: "proto"
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1,subdir=proto"

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
